---
title: "Labor Income : Average vs Median, Gini Coefficient"
output: html_document
date: "2023-04-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
median <- c(17.5, 17.7, 18.8, 20.8, 21.6, 23.0, 23.4, 24.6, 26.0, 27.2, 28.3, 28.9, 29.7)
average <- c(25.8, 26.4, 28.2, 29.8, 30.7, 32.0, 32.8, 33.9, 35.4, 36.6, 37.6, 38.5, 40.4) 
gini <- c(0.494, 0.506, 0.489, 0.475, 0.474, 0.465, 0.466, 0.46, 0.456, 0.446, 0.438, 0.440, 0.445)
year <- 2009:2021
L <- length(year)
average_diff <- average[L] - average[1]
median_diff <- median[L] - median[1]
```

## Average vs Median

```{r average vs Median, echo = FALSE, fig.width = 8, fig.height = 6}
par(family = "KoPubWorldDotum Medium")
plot(x = year, y = average, ann = FALSE, type = "b", pch = 17, col = "red", ylim = c(15, 45))
lines(x = year, y = median, type = "b", pch = 17, col = "blue")
text(x = year[c(1, L)], average[c(1, L)], labels = average[c(1, L)], pos = 3)
text(x = year[c(1, L)], median[c(1, L)], labels = median[c(1, L)], pos = 3)
text(x = 2017, y = (average[9] + median[9]) / 2, labels = paste0("평균소득이 ", round(average_diff, digits = 1), "백만 원 증가할 동안,\n 중위소득은 ", round(median_diff, digits = 1), "백만 원 증가함."), srt= 15)
text(x = 2017, y = 16, labels = "2009-2021 : 국세통계연보 급여총계")
title(main = "평균소득과 중위소득", cex.main = 1.8, family = "KoPubWorldDotum Bold")
title(xlab = "연도", ylab = "금여총계(백만 원)")
```

## Gini Coefficients

```{r gini, echo=FALSE, fig.width = 8, fig.height = 6}
plot(x = year, y = gini, ann = FALSE, type = "b", pch = 17, col = "red", ylim = c(0.35, 0.55))
text(x = year[c(1, 2, L-2, L)], y = gini[c(1, 2, L-2, L)], labels = round(gini[c(1, 2, L-2, L)], digits = 3), pos = c(1, 3, 1, 3))
title(main = "급여총계의 지니계수", cex.main = 1.8, family = "KoPubWorldDotum Bold")
title(xlab = "연도", ylab = "지니계수")
```

