---
title: "Loops"
author: "coop711"
date: '2018 5 30 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("./S3.RData")
```

## Expected Values

```{r}
die <- 1:6
```

## `expand.grid`

```{r}
rolls <- expand.grid(die, die)
rolls
expand.grid(1:2, 1:2, 1:2)
rolls$value <- rolls$Var1 + rolls$Var2
head(rolls, 3)
prob <- c("1" = 1/8, "2" = 1/8, "3" = 1/8, "4" = 1/8, "5" = 1/8, "6" = 3/8)
prob
rolls$Var1
prob[rolls$Var1]
rolls$prob1 <- prob[rolls$Var1]
rolls$prob2 <- prob[rolls$Var2]
rolls
rolls$prob <- rolls$prob1 * rolls$prob2
rolls
sum(rolls$value * rolls$prob)
```

### Slot Machine

```{r}
wheel <- c("DD", "7", "BBB", "BB", "B", "C", "0")
combos <- expand.grid(wheel, wheel, wheel, 
                      stringsAsFactors = FALSE)
combos
get_symbols <- function() {
  wheel <- c("DD", "7", "BBB", "BB", "B", "C", "0")
  sample(wheel, 
         size = 3, 
         replace = TRUE,
         prob = c(0.03, 0.03, 0.06, 0.1, 0.25, 0.01, 0.52))
}
prob <- c("DD" = 0.03, 
          "7" = 0.03, 
          "BBB" = 0.06, 
          "BB" = 0.1, 
          "B" = 0.25, 
          "C" = 0.01, 
          "0" = 0.52)
combos$prob1 <- prob[combos$Var1]                      
combos
combos$prob2 <- prob[combos$Var2]   
combos$prob3 <- prob[combos$Var3]   
head(combos, 3)
combos$prob <- combos$prob1 * combos$prob2 * combos$prob3
head(combos, 3)
sum(combos$prob)
symbols <- c(combos[1, 1], combos[1, 2], combos[1, 3])
score(symbols)
```

## for Loops

```{r}
for (value in c("My", "First", "for", "loop")) {
  print("one run")
}
value
for (value in c("My", "First", "for", "loop")) {
  print(value)
}
for (word in c("My", "First", "for", "loop")) {
  print(word)
}
for (string in c("My", "First", "for", "loop")) {
  print(string)
}
for (i in c("My", "First", "for", "loop")) {
  print(i)
}
for (value in c("My", "First", "for", "loop")) {
  value
}
chars <- vector(length = 4)
chars
words <- c("My", "First", "for", "loop")
for (i in 1:4) {
  chars[i] <- words[i]
}
chars
```

```{r}
combos$prize <- NA
head(combos, 3)
for (i in 1:nrow(combos)) {
  symbols <- c(combos[i, 1], combos[i, 2], combos[i, 3])
  combos$prize[i] <- score(symbols)
}
head(combos, 3)
sum(combos$prize * combos$prob)
score <- function(symbols) {
  diamonds <- sum(symbols == "DD")
  cherries <- sum(symbols == "C")
  
  # identify case
  # since diamonds are wild, only nondiamonds
  # matter for three of a kind and all bars
  slots <- symbols[symbols != "DD"]
  same <- length(unique(slots)) == 1
  bars <- slots %in% c("B", "BB", "BBB")
  
  # assign prize
  if (diamonds == 3) {
    prize <- 100
  } else if (same) {
    payouts <- c("7" = 80, 
                 "BBB" = 40, 
                 "BB" = 25, 
                 "B" = 10, 
                 "C" = 10, 
                 "0" = 0)
    prize <- unname(payouts[slots[1]])
  } else if (all(bars)) {
    prize <- 5
  } else if (cherries > 0) {
    # diamonds count as cherries
    # so long as there is one real cherry
    prize <- c(0, 2, 5)[cherries + diamonds + 1]
  } else {
    prize <- 0
  }
  
  # double for each diamond
  prize * 2^diamonds
}
score(c("BB", "DD", "B"))
for (i in 1:nrow(combos)) {
  symbols <- c(combos[i, 1], combos[i, 2], combos[i, 3])
  combos$prize[i] <- score(symbols)
}
head(combos, 3)
sum(combos$prize * combos$prob)
```

```{r}
save.image(file = "./Loops.RData")
```