b1 <- barplot(as.matrix(1:3, ncol = 1), 
              axes = FALSE,
              width = 1, 
              xlim = c(-0.5, 3.5), 
              ylim = c(0, 6.5), 
              beside = FALSE, 
              col = "white")
text(x = b1 + 0.55, 
     y = cumsum(1:3), 
     labels = c("x1", "x1 + x2", "x1 + x2 + x3"), 
     adj = 0)
text(x = b1, 
     y = cumsum(1:3) - (1:3)/2, 
     labels = "x")
text(x = b1 + 0.7, 
     y = cumsum(1:3) - (1:3)/2, 
     labels = c("x1 - x1/2", "x1 + x2 - x2/2", "x1 + x2 + x3 - x3/2"), 
     adj = 0)