---
title: "King Sejong's National Referendum on Tax Reform (R-Base Plot)"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

## Data 

원자료는 [세종실록](http://sillok.history.go.kr/id/kda_11208010_005), 요약표는 오기수 교수의 논문에서.

```{r, data, echo = FALSE, message = FALSE, results = 'hide'}
knitr::opts_chunk$set(echo = TRUE)
# library(pander)
library(knitr)
library(extrafont)
# panderOptions('table.split.table', Inf)
load("sejong_poll_data_kr.RData")
str(sejong.poll.kr)
```

```{r, kable, echo = FALSE, results = 'asis'}
v.names.kr <- c("집계", "찬반", "계급", "지역", "관료여부")
# kable(sejong.poll.kr[c(4, 3, 5, 2, 1)])
kable(sejong.poll.kr[c(4, 3, 5, 2, 1)], col.names = v.names.kr[c(4, 3, 5, 2, 1)], align = c(rep('c', 4), 'r'))
```

<P style = "page-break-before:always">

## 전체 찬반

```{r, overall votes}
# pander(format(tbl.vote, big.mark = ","))
kable(t(as.matrix(format(tbl.vote, big.mark = ","))), caption = "전체 찬반", align = 'c')
kable(t(as.table(format(tbl.vote, big.mark = ","))), caption = "전체 찬반", align = 'c')
kable(t(as.table(format(prop.table(tbl.vote)*100, digits = 3, nsmall = 1))), caption = "전체 찬반(%)", align = 'c')
```

<P style = "page-break-before:always">

### 원형그래프

```{r, pie for total, fig.width = 5, fig.height = 5}
par(family = "KoPubWorldDotum Medium")
gray.2 <- gray.colors(12)[c(12, 7)]
rainbow.2 <- rainbow(2)[2:1]
pie(tbl.vote, col = rainbow.2)
title(main = "전체 찬반")
text(x = 0, y = c(0.4, -0.4), labels = format(tbl.vote, big.mark = ","))
# dev.copy(png, "../pics/sejong_total_pie.png", width = 480, height = 480)
# dev.off()
```

<P style = "page-break-before:always">

# 계급 및 지역별 찬반

## 계급별 찬반

```{r, vote by classes}
kable(format(vote.class, big.mark = ","), align = "r", caption = "계급별 찬반")
kable(format(prop.table(vote.class, margin = 2)*100, digits = 3, nsmall = 1), align = "r", caption = "계급별 찬반(%)")
```

## 품관촌민 별도 분석

품관촌민의 수효가 상대적으로 많아서

```{r, vote by class2}
kable(format(vote.class.2, big.mark = ","), align = rep("r", 2), caption = "품관촌민")
```

소계를 교차표의 주변에 계산

```{r, addmargins}
kable(format(vote.class.2.am, big.mark = ","), caption = "관료와 품관촌민(소계)", align = rep("r", 3))
```

백분율을 계산하여 주변에 집계. 

```{r, Percentage}
kable(format(prop.table(vote.class.2, margin = 2)*100, digits = 3, nsmall = 1), caption = "관료와 품관촌민(%)", align = rep("r", 3))
```

<P style = "page-break-before:always">

### 원형그래프

```{r, pie for class2, message = FALSE, fig.width = 10, fig.height = 5}
par(family = "KoPubWorldDotum Medium")
par(mfrow = c(1, 2))
pie(vote.class.2[, 1], labels = c("찬성", "반대"), col = rainbow.2)
title(main = "관료의 찬반")
text(x = 0, y = c(0.4, -0.4), labels = vote.class.2[, 1])
pie(vote.class.2[, 2], labels = c("찬성", "반대"), col = rainbow.2)
title(main = "품관촌민의 찬반")
text(x = 0, y = c(0.4, -0.4), labels = format(vote.class.2[, 2], big.mark = ","))
# dev.copy(png, "../pics/sejong_bureaus_commons_pie.png", width = 960, height = 480)
# dev.off()
par(mfrow = c(1, 1))
```

```{r, coord_polar.2, message = FALSE, fig.width = 8, fig.height = 4}
vote.class.2.df <- as.data.frame(vote.class.2)
v.names.class.kr <- c("찬반", "계급", "집계")
kable(format(vote.class.2.df, big.mark = ","), align = c('c', 'c', 'r'), col.names = v.names.class.kr, caption = "관료와 품관촌민")
vote.bureaus.df <- subset(vote.class.2.df, vote.class.2.df$class.2 == "관료", select = c("vote", "Freq"))
kable(format(vote.bureaus.df, big.mark = ","), align = 'r', col.names = v.names.class.kr[-2], caption = "관료의 찬반")
vote.commons.df <- subset(vote.class.2.df, vote.class.2.df$class.2 == "품관촌민", select = c("vote", "Freq"))
kable(format(vote.commons.df, big.mark = ","), align = 'r', row.names = FALSE, col.names = v.names.class.kr[-2], caption = "품관촌민의 찬반")
```

<P style = "page-break-before:always">

## 지역별 찬반

### 관료와 품관촌민

```{r, by region}
kable(vote.region.bureaus, caption = "관료들의 지역별 찬반")
kable(format(prop.table(vote.region.bureaus, margin = 2)*100, digits = 3, nsmall = 1), align = rep("r", 9), caption = "관료들의 지역별 찬반(%)")
kable(format(vote.region.commons, big.mark = ","), align = rep("r", 9), caption = "품관촌민들의 지역별 찬반")
kable(format(prop.table(vote.region.commons, margin = 2)*100, digits = 1, nsmall = 1), align = rep("r", 9), caption = "품관촌민들의 지역별 찬반(%)")
```

## 서울의 찬반

```{r, Seoul}
kable(vote.seoul.class, caption = "서울의 찬반")
kable(format(prop.table(vote.seoul.class, margin = 2)*100, digits = 1, nsmall = 1), align = rep("r", 3), caption = "서울의 찬반(%)")
```

<P style = "page-break-before:always">

### 막대그래프

서울의 계급별 찬반을 `barplot`으로 그려봄. `text()`의 좌표는 `locator()`로 찾아냄.

```{r, seoul by class, fig.width = 6, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
barplot(vote.seoul.class, col = rainbow.2)
title(main = "서울의 찬반")
text(x = c(0.7, 1.9, 1.9, 3.1, 3.1), y = c(120, 450, 135, 500, 220), labels = c("194","393", "259", "117", "443"))
legend("topleft", inset = 0.05, fill = rainbow.2, legend = c("찬성", "반대"))
# dev.copy(png, "../pics/sejong_seoul_barplot.png", width = 480, height = 360)
# dev.off()
```

<P style = "page-break-before:always">

### mosaic plot

```{r, mosaicplot for seoul, fig.width = 6, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
mosaicplot(t(vote.seoul.class), col = rainbow.2, main = "서울의 찬반", xlab = "계급" , ylab = "찬반")
# dev.copy(png, "../pics/sejong_seoul_mosaic.png", width = 480, height = 360)
# dev.off()
```

<P style = "page-break-before:always">

## 지역별 관료들의 찬반(서울 제외)

```{r, local bureaus}
kable(vote.region.bureaus[, -1], caption = "지역별 관료들의 찬반(서울 제외)")
kable(format(prop.table(vote.region.bureaus[, -1], margin = 2)*100, digits = 1, nsmall = 1), align = "r", caption = "지역별 관료들의 찬반(서울 제외, %)")
```

### 막대그래프

```{r, barplot for regional bureaus, fig.width = 9, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
barplot(vote.region.bureaus[, -1], beside = FALSE, col = rainbow.2)
title(main = "지방 관료들의 찬반")
legend("topleft", inset = 0.05, fill = rainbow.2, legend = c("찬성", "반대"))
# dev.copy(png, "../pics/sejong_bureaus.png", width = 720, height = 360)
# dev.off()
```

<P style = "page-break-before:always">

### mosaic plot

```{r, mosaic for local bureaus, fig.width = 9, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
mosaicplot(t(vote.region.bureaus[, -1]), col = rainbow.2, main = "", xlab = "지역", ylab = "찬반")
title(main = "지방 관료들의 찬반")
# dev.copy(png, "../pics/sejong_bureaus_mosaic.png", width = 720, height = 360)
# dev.off()
```

<P style = "page-break-before:always">

## 품관촌민들의 지역별 찬반

### 막대그래프

```{r, barplot for commons, fig.width = 12, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
barplot(vote.region.commons, beside = FALSE, col = rainbow.2, axes = FALSE)
axis(2, at = seq(0, 30000, by = 5000), labels = c("0", "", "1만", "", "2만", "", "3만"), las = 1)
title(main = "품관촌민들의 지역별 찬반")
legend("topleft", inset = 0.05, fill = rainbow.2, legend = c("찬성", "반대"))
# dev.copy(png, "../pics/sejong_commons_barplot.png", width = 720, height = 360)
# dev.off()
```

<P style = "page-break-before:always">

### mosaic plot

```{r, mosaicplot for commons, fig.width = 9, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
mosaicplot(t(vote.region.commons), col = rainbow.2, main = "품관촌민의 지역별 찬반", xlab = "지역", ylab = "찬반")
# dev.copy(png, "../pics/sejong_commons_mosaic.png", width = 720, height = 360)
# dev.off()
```

<P style = "page-break-before:always">

## 충청도

관료들의 찬반과 품관촌민의 찬반이 다른 곳.

```{r, chungcheong}
kable(format(vote.chung.class, big.mark = ","), caption = "충청도 사례", align = "r")
kable(format(prop.table(vote.chung.class, margin = 2)*100, digits = 3, nsmall = 1), caption = "충청도 사례", align = "r")
```

### 막대그래프

```{r, barplot for chungcheong, fig.width = 6, fig.height = 4.5}
par(mar = c(5.1, 4.1, 4.1, 8.1), xpd = TRUE, family = "KoPubWorldDotum Medium")
barplot(prop.table(vote.chung.class, margin = 2), col = rainbow.2, ylim = c(0,  1.1), axes = FALSE)
axis(side = 2, at = c(0, 0.5, 1.0), labels = c("0", "50%", "100%"), las = 1)
title(main = "충청도의 계급별 찬반 비율")
legend("right", inset = -0.3, fill = rainbow.2, legend = c("찬성", "반대"))
text(x = c(0.6, 1.85, 1.85, 3.1, 3.1), y = c(0.5, 0.3, 0.8, 0.15, 0.65), labels = format(c(2, 35, 26, 6982, 14013), big.mark = ","))
# dev.copy(png, "../pics/sejong_chungcheong_barplot.png", width = 480, height = 360)
# dev.off()
```

<P style = "page-break-before:always">

### mosaic plot

수효의 차이가 너무 커서 비교하기 어려움. '대신 등' 제외하고 작업

```{r, mosaic chungcheong, fig.width = 9, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
mosaicplot(t(vote.chung.class[, -1]), col = rainbow.2, main = "", xlab = "계급", ylab = "찬반")
title(main = "충청도의 찬반")
# dev.copy(png, "../pics/sejong_chungcheong_mosaic.png", width = 480, height = 360)
# dev.off()
```

## 자료 정리

```{r, save}
save.image(file = "./sejong_ggplot.RData")
```

