---
title: "King Sejong's National Referendum on Tax Reform (R-Base Plot, piping)"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r, data, echo = FALSE, message = FALSE, results = 'hide'}
knitr::opts_chunk$set(echo = TRUE)
# library(pander)
library(knitr)
library(magrittr)
library(extrafont)
# panderOptions('table.split.table', Inf)
```

## Data 

원자료는 [세종실록](http://sillok.history.go.kr/id/kda_11208010_005), 요약표는 오기수 교수의 논문에서.

```{r}
load("sejong_poll_data_kr_v2.RData")
sejong_poll_kr %>% str
```

```{r, kable, echo = TRUE, results = 'markup'}
v_names_kr <- c("집계", "찬반", "계급", "지역", "신분")
# kable(sejong_poll_kr[c(4, 3, 5, 2, 1)])
sejong_poll_kr %>%
  `[`(c(4, 3, 5, 2, 1)) %>%
  kable(col.names = v_names_kr %>% `[`(c(4, 3, 5, 2, 1)), 
        align = c(rep('c', 4), 'r'))
```

<P style = "page-break-before:always">

## 전체 찬반

### 집계

```{r, overall votes}
vote_total %>%
  as.matrix %>%
  t %>%
  cbind("계" = rowSums(.)) %>%
  format(big.mark = ",") %>%
  kable(caption = "전체 찬반", align = "r")
vote_total %>%
  prop.table %>%
  `*`(100) %>%
  as.matrix %>%
  t %>%
  cbind("계" = rowSums(.)) %>%
  format(digits = 3, nsmall = 1) %>%
  kable(caption = "전체 찬반(%)", align = "r")
```

<P style = "page-break-before:always">

### 원형그래프

```{r, pie for total, fig.width = 5, fig.height = 5}
par(family = "KoPubWorldDotum Medium")
gray_2 <- gray.colors(12)[c(12, 7)]
rainbow_2 <- rainbow(2)[2:1]
vote_total %>%
  pie(col = rainbow_2)
title(main = "전체 찬반")
text(x = 0, y = c(0.4, -0.4), labels = format(vote_total, big.mark = ","))
# dev.copy(png, "../pics/sejong_total_pie.png", width = 480, height = 480)
# dev.off()
```

<P style = "page-break-before:always">

## 계급 및 지역별 찬반

### 계급별 찬반 분할표

```{r, vote by classes}
vote_class %>%
  cbind("계" = rowSums(.)) %>%
  rbind("계" = colSums(.)) %>%
  format(big.mark = ",") %>%
  kable(align = "r", caption = "계급별 찬반")
vote_class %>%
  prop.table(margin = 2) %>%
  `*`(100) %>%
  format(digits = 3, nsmall = 1) %>%
  kable(align = "r", caption = "계급별 찬반(%)")
```

### 품관촌민 별도 분석

품관촌민의 수효가 상대적으로 많아서

```{r, vote by class2}
vote_class_2 %>%
  cbind("계" = rowSums(.)) %>%
  rbind("계" = colSums(.)) %>%
  format(big.mark = ",") %>%
  kable(caption = "관료와 품관촌민", align = "r")
```

백분율로 계산

```{r}
vote_class_2 %>%
  prop.table(margin = 2) %>%
  `*`(100) %>%
  format(digits = 3, nsmall = 1) %>%
  kable(caption = "관료와 품관촌민(%)", align = "r")
```

### 원형그래프

```{r, pie for class2, message = FALSE, fig.width = 10, fig.height = 5}
par(family = "KoPubWorldDotum Medium")
par(mfrow = c(1, 2))
vote_class_2 %>%
  `[`(, 1) %>%
  pie(labels = c("찬성", "반대"), col = rainbow_2)
title(main = "관료의 찬반")
text(x = 0, y = c(0.4, -0.4), labels = vote_class_2[, 1])
vote_class_2 %>%
  `[`(, 2) %>%
  pie(labels = c("찬성", "반대"), col = rainbow_2)
title(main = "품관촌민의 찬반")
text(x = 0, y = c(0.4, -0.4), labels = format(vote_class_2[, 2], big.mark = ","))
# dev.copy(png, "../pics/sejong_bureaus_commons_pie.png", width = 960, height = 480)
# dev.off()
par(mfrow = c(1, 1))
```

<P style = "page-break-before:always">

## 지역별 찬반

### 관료

```{r, by region}
#> 소계를 추가한 관료들의 지역별 찬반 분할표 출력
vote_region_bureaus %>% 
  cbind("계" = rowSums(.)) %>%
  rbind("계" = colSums(.)) %>%
  format(big.mark = ",") %>%
  kable(caption = "관료들의 지역별 찬반", align = "r")
#> 지역별 찬반 벡분율
vote_region_bureaus %>%
  prop.table(margin = 2) %>%
  `*`(100) %>%
  format(digits = 3, nsmall = 1) %>%
  kable(caption = "관료들의 지역별 찬반(%)", align = "r")
```

### 품관촌민

```{r}
#> 소계를 추가한 품관촌민의 지역별 찬반 분할표 출력
vote_region_commons %>%
  cbind("계" = rowSums(.)) %>%
  rbind("계" = colSums(.)) %>%
  format(big.mark = ",") %>%
  kable(caption = "품관촌민들의 지역별 찬반", align = "r")
#> 지역별 찬반 벡분율
vote_region_commons %>%
  prop.table(margin = 2) %>%
  `*`(100) %>%
  format(digits = 1, nsmall = 1) %>%
  kable(caption = "품관촌민들의 지역별 찬반(%)", align = "r")
```

## 서울의 찬반

```{r}
vote_seoul_class %>% 
  cbind("계" = rowSums(.)) %>%
  rbind("계" = colSums(.)) %>%
  format(big.mark = ",") %>%
  kable(caption = "서울의 찬반")
vote_seoul_class %>%
  prop.table(margin = 2) %>%
  `*`(100) %>%
  format(digits = 1, nsmall = 1) %>%
  kable(align = "r", caption = "서울의 찬반(%)")
```

<P style = "page-break-before:always">

### 막대그래프

서울의 계급별 찬반을 `barplot`으로 그려봄. `text()`의 좌표는 `locator()`로 찾아냄.

```{r, seoul by class, fig.width = 6, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
# %>%
b_seoul <- vote_seoul_class %>% 
  barplot(col = rainbow_2, yaxt = "n") 
axis(side = 2, 
     at = vote_seoul_class %>% apply(MARGIN = 2, cumsum), 
     labels = vote_seoul_class %>% apply(MARGIN = 2, cumsum), las = 2)
title(main = "서울의 찬반") 
y_text <- c(vote_seoul_class[1, ] / 2, vote_seoul_class[1, ] + vote_seoul_class[2, ] / 2) 
text(x = rep(b_seoul, times = 2), 
     y = y_text, 
     labels = c(vote_seoul_class[1, ], vote_seoul_class[2, ]))
legend("topleft", inset = 0.05, fill = rainbow_2, legend = c("찬성", "반대"))
# dev.copy(png, "../pics/sejong_seoul_barplot.png", width = 480, height = 360)
# dev.off()
```

<P style = "page-break-before:always">

### mosaic plot

```{r, mosaicplot for seoul, fig.width = 6, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
vote_seoul_class %>%
  t %>%
  mosaicplot(col = rainbow_2, 
             main = "서울의 찬반", 
             xlab = "계급", 
             ylab = "찬반",
             off = 1)
# dev.copy(png, "../pics/sejong_seoul_mosaic.png", width = 480, height = 360)
# dev.off()
```

<P style = "page-break-before:always">

## 관료들의 지역별 찬반(서울 제외)

```{r, local bureaus}
vote_region_bureaus[, -1] %>%
  kable(caption = "지역별 관료들의 찬반(서울 제외)")
vote_region_bureaus[, -1] %>%
  prop.table(margin = 2) %>%
  `*`(100) %>%
  format(digits = 1, nsmall = 1) %>%
  kable(align = "r", caption = "지역별 관료들의 찬반(서울 제외, %)")
```

### 막대그래프

```{r, barplot for regional bureaus, fig.width = 9, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
vote_region_bureaus[, -1] %>%
  barplot(beside = FALSE, col = rainbow_2)
title(main = "지방 관료들의 찬반")
legend("topleft", inset = 0.05, fill = rainbow_2, legend = c("찬성", "반대"))
# dev.copy(png, "../pics/sejong_bureaus.png", width = 720, height = 360)
# dev.off()
```

<!--
<P style = "page-break-before:always">
-->

### mosaic plot

```{r, mosaic for local bureaus, fig.width = 9, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
vote_region_bureaus[, -1] %>%
  t %>%
  mosaicplot(col = rainbow_2, 
             main = "", 
             xlab = "지역", 
             ylab = "찬반",
             off = c(3, 1))
title(main = "지방 관료들의 찬반")
# dev.copy(png, "../pics/sejong_bureaus_mosaic.png", width = 720, height = 360)
# dev.off()
```

<P style = "page-break-before:always">

## 품관촌민들의 지역별 찬반

### 막대그래프

```{r, barplot for commons, fig.width = 12, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
vote_region_commons %>%
  barplot(beside = FALSE, col = rainbow_2, axes = FALSE)
axis(2, at = seq(0, 30000, by = 5000), labels = c("0", "", "1만", "", "2만", "", "3만"), las = 1)
title(main = "품관촌민들의 지역별 찬반")
legend("topleft", inset = 0.05, fill = rainbow_2, legend = c("찬성", "반대"))
# dev.copy(png, "../pics/sejong_commons_barplot.png", width = 720, height = 360)
# dev.off()
```

<P style = "page-break-before:always">

### mosaic plot

```{r, mosaicplot for commons, fig.width = 9, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
vote_region_commons %>%
  t %>%
  mosaicplot(col = rainbow_2, 
             main = "품관촌민의 지역별 찬반", 
             xlab = "지역", 
             ylab = "찬반",
             off = c(3, 1))
# dev.copy(png, "../pics/sejong_commons_mosaic.png", width = 720, height = 360)
# dev.off()
```

<P style = "page-break-before:always">

## 충청도

관료들의 찬반과 품관촌민의 찬반이 다른 곳.

```{r, chungcheong}
vote_chung_class %>%
  format(big.mark = ",") %>%
  kable(caption = "충청도 사례", align = "r")
vote_chung_class %>%
  prop.table(margin = 2) %>%
  `*`(100) %>%
  format(digits = 3, nsmall = 1) %>%
  kable(caption = "충청도 사례", align = "r")
```

<P style = "page-break-before:always">

### 막대그래프

```{r, barplot for chungcheong, fig.width = 6, fig.height = 4.5}
par(mar = c(5.1, 4.1, 4.1, 8.1), xpd = TRUE, family = "KoPubWorldDotum Medium")
vote_chung_class %>%
  prop.table(margin = 2) %>%
  barplot(col = rainbow_2, ylim = c(0,  1.1), axes = FALSE)
axis(side = 2, at = c(0, 0.5, 1.0), labels = c("0", "50%", "100%"), las = 1)
title(main = "충청도의 계급별 찬반 비율")
legend("right", inset = -0.3, fill = rainbow_2, legend = c("찬성", "반대"))
text(x = c(0.6, 1.85, 1.85, 3.1, 3.1), y = c(0.5, 0.3, 0.8, 0.15, 0.65), labels = format(c(2, 35, 26, 6982, 14013), big.mark = ","))
# dev.copy(png, "../pics/sejong_chungcheong_barplot.png", width = 480, height = 360)
# dev.off()
```

<P style = "page-break-before:always">

### mosaic plot

수효의 차이가 너무 커서 비교하기 어려움. '대신 등' 제외하고 작업

```{r, mosaic chungcheong, fig.width = 9, fig.height = 4.5}
par(family = "KoPubWorldDotum Medium")
vote_chung_class[, -1] %>%
  t %>%
  mosaicplot(col = rainbow_2, main = "", xlab = "계급", ylab = "찬반")
title(main = "충청도의 찬반")
# dev.copy(png, "../pics/sejong_chungcheong_mosaic.png", width = 480, height = 360)
# dev.off()
```

## 자료 정리

```{r, save}
save.image(file = "./sejong_plot.RData")
```

