---
title: "Team Allocation for Basic Programming in R "
author: "coop711"
date: "2020-05-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!--
### Data

```{r, data}
library(magrittr)
library(xlsx)
library(knitr)
class_roll <- "../data/class_roll200503.xlsx" %>%
  read.xlsx(sheetIndex = 1,
             startRow = 2, endRow = 95,
             colIndex = c(3:7, 9),
             colClasses = rep("character", 6),
            encoding = "UTF-8",
            stringsAsFactors = FALSE)
names(class_roll) <- c("dept", "id", "name", "year", "email", "cell_no")
str(class_roll)
```

### 랜덤하게 31 Team으로 나누기

```{r, team id, echo = TRUE}
set.seed(2)
N <- nrow(class_roll)
group <- sample(1:N) %% 31
class_roll$group <- factor(group, 
                           levels = 0:30, 
                           labels = paste("Team", 1:31, sep = "_"))
kable(class_roll)
```

### 학번

```{r, entrance}
kable(table("그룹" = class_roll$group, 
            "학번" = substr(class_roll$id, 
                          start = 1, stop = 4)))
```

### email 서비스업체

```{r, e_mail}
email_list <- strsplit(class_roll$email, "@", fixed = TRUE)
mail_com <- sapply(email_list, `[`, 2)
kable(table("팀" = class_roll$group,
            "e-mail" = mail_com))
```

### 학년 분포

```{r, School Year, echo = TRUE}
kable(table("팀"= class_roll$group, "학년" = class_roll$year))
```

### 성씨 분포

```{r, name}
f_name <- substring(class_roll$name, 
                    first = 1, last = 1)
kable(table("팀" = class_roll$group,
            "Family Name" = f_name))
```

#### 많이 나오는 성씨

```{r, frequent family name, echo = TRUE}
f_name <- substring(class_roll$name, 
                    first = 1, 
                    last = 1)
# f_name %in% c("김","이","박")
f_name_f <- factor(ifelse(f_name %in% c("김", "이", "박", "최"), 
                          f_name, "기타"), 
                   levels = c("김", "이", "박", "최", "기타"))
kable(table("팀" = class_roll$group, "Family Name" = f_name_f))
```

-->
### Team 별로 모으기

```{r, list, echo = FALSE, results = 'markup'}
gr_names_o <- order(class_roll$group, class_roll$name)
names_by_gr <- class_roll[gr_names_o, 
                          c("group", "dept", "id", "name", "year", "email", "cell_no")]
kable(names_by_gr[-3], row.names = FALSE)
```

### 출력

```{r}
write.table(names_by_gr[, c(1, 3:7, 2)], 
            file ="../data/team_roll.txt", row.names = FALSE)
```

<!--
#### Team 1

```{r, team 1}
Team_1_names <- names_by_gr[names_by_gr$group == "Team 1", c("id", "name")]
kable(Team_1_names)
```

#### Team 2

```{r, team 2}
Team_2_names <- names_by_gr[names_by_gr$group == "Team 2", c("id", "name")]
kable(Team_2_names)
```

#### Team 3

```{r, team 3}
Team_3_names <- names_by_gr[names_by_gr$group == "Team 3", c("id", "name")]
kable(Team_3_names)
```

#### Team 4

```{r, team 4}
Team_4_names <- names_by_gr[names_by_gr$group == "Team 4", c("id", "name")]
kable(Team_4_names)
```

```{r, save}
save.image("./team_1801_data_out.RData")
```
-->