---
title: "TED DS200405"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
# install.packages("readr", repos = "https://cran/rstudio.com")
library(xlsx)
library(pander)
library(knitr)
library(dplyr)
library(magrittr)
panderOptions('table.split.table', Inf)
options(width = 180)
```

<!--
# Data
-->

```{r, data, echo = FALSE, results = "hide"}
source("./TED_data.R")
ted0405<- TED_data(data = "../data/TED200405.xlsx", 
                   nrow = 110, 
                   date = "2020-04-06 09:00:00")
```

# 제출/미제출

제출시간이 기록되지 않은 사람은 미제출.

```{r, echo = FALSE, results = "markup"}
pander(table(ted0405$group, ted0405$submit))
pander(chisq.test(table(ted0405$group, ted0405$submit), 
                  simulate.p.value = TRUE))
```

# 제출 시간의 분포

마감 시간으로부터 얼마나 일찍 제출하는지 일 단위와 시간 단위로 측정하여 살펴보았다. 

## 시간 단위 기초통계량

```{r, echo = FALSE}
# ted0405$hours
summary(ted0405$hours)
stem(ted0405$hours)
max(ted0405$hours, na.rm = TRUE)
```

## 일 단위 마감 시간으로부터 제출 시간의 분포

```{r, echo = FALSE}
par(family = "HCR Dotum LVT")
pander(table(cut(ted0405$days, breaks = c(0:14), include.lowest = TRUE)), caption = "일 단위")
barplot(rev(table(cut(ted0405$days, breaks = c(0:14), include.lowest = TRUE))), 
        space = 0,
        names.arg = rep(c("월", "화","수", "목", "금", "토","일"), 2))
title(main = "일 단위 퀴즈 제출 횟수")
```

## 시간 단위 마감 시간으로부터 제출 시간의 분포

```{r, echo = FALSE}
breaks <- c(seq(0, 48, by = 24), 49:54, seq(72, 168, by = 24))
breaks2 <- c(seq(0, 48, by = 24), 49:58, seq(72, 168, by = 24))
breaks3 <- c(0:10, seq(24, 336, by = 24))
breaks4 <- c(seq(0, 168, by = 24), 169:178, seq(192, 336, by = 24))
pander(table(cut(ted0405$hours, breaks = breaks3, include.lowest = TRUE)), caption = "시간 단위")
```

## 시간 당 제출 건수의 분포

```{r, echo = FALSE, fig.width = 12}
par(family = "HCR Dotum LVT")
widths <- c(rep(24, 4), 16, rep(1, 10), rep(24, 1), 14, rep(1, 10))
widths2 <- c(rep(24, 4), 16, rep(1, 10), rep(24, 2))
widths3 <- c(rep(24, 13), 14, rep(1, 10))
widths4 <- rev(diff(breaks4))
# freqs <- table(cut(ted0405$hours, breaks = breaks2, include.lowest = TRUE))
freqs2 <- table(cut(ted0405$hours, breaks = breaks2, include.lowest = TRUE))
freqs3 <- table(cut(ted0405$hours, breaks = breaks3, include.lowest = TRUE))
freqs4 <- table(cut(ted0405$hours, breaks = breaks4, include.lowest = TRUE))
# heights <- freqs / diff(breaks)
heights2 <- freqs2 / diff(breaks2)
heights3 <- freqs3 / diff(breaks3)
heights4 <- freqs4 / diff(breaks4)
# names_args <- c("수", "목", "금", "토", "일", rep("", 10), "월", "화", rep("", 10))
names_args2 <- c("수", "목", "금", "토", "일", rep("", 10), "월", "화")
names_args3 <- c(rep(c("월", "화", "수", "목", "금", "토", "일"), 2), rep("", 10))
names_args4 <- c("월", "화", "수", "목", "금", "토", "일", rep("", 10), "월", "화", "수", "목", "금", "토", "일")
# barplot(height = rev(heights), width = widths, 
#         space = 0,
#         names.arg = names_args)
# barplot(height = rev(heights2), width = widths2, 
#         space = 0,
#         names.arg = names_args2)
barplot(height = rev(heights3), width = widths3, 
        space = 0,
        names.arg = names_args3)
title(main = "시간당 TED 댓글 제출 분포")
# arrows(x0 = 8, y0 = 3.6, x1 = 16, y1 = 1.2, length = 0.16, code = 2, col = "red", lwd = 1.5)
# text(x = 5, y = 4, labels = "오후 6시", srt = 16, col = "red")
arrows(x0 = 308, y0 = 4.6, x1 = 324, y1 = 0.8, length = 0.16, code = 2, col = "red", lwd = 1.5)
text(x = 300, y = 5.6, labels = "오후\n2시", srt = 16, col = "red")
# arrows(x0 = 128, y0 = 3.6, x1 = 136, y1 = 1.2, length = 0.16, code = 2, col = "red", lwd = 1.5)
# text(x = 125, y = 4, labels = "오후 6시", srt = 16, col = "red")
# arrows(x0 = 152, y0 = 5.6, x1 = 160, y1 = 1.2, length = 0.16, code = 2, col = "red", lwd = 1.5)
# text(x = 149, y = 6, labels = "오후 2시", srt = 16, col = "red")
```

# 늦게 작성한 사람과 일찍 작성한 사람 비교

마감 일주일 전에 올린 사람과 마감 일주일 이후에 올린 사람들의 특성 비교

## 랜덤화 효과

```{r, echo = FALSE}
pander(table(ted0405$group, ted0405$bird))
pander(chisq.test(table(ted0405$group, ted0405$bird)))
```

# 댓글의 양 

```{r, echo = FALSE}
stem(ted0405$n_chars, scale = 0.5)
```

## 그룹별 댓글 크기 비교

### 댓글의 양 비교

```{r, echo = FALSE}
pander(tapply(ted0405$n_chars, ted0405$group, summary))
```

### Box Plot

```{r, echo = FALSE}
par(family = "HCR Dotum LVT")
plot(n_chars ~ group, data = ted0405, 
     main = "그룹별 댓글의 양 비교", 
     xlab = "제출 시점", ylab = "글자 수")
```

### t-test

```{r, echo = FALSE}
pander(t.test(n_chars ~ group, data = ted0405))
```

## 마감일 기준 댓글의 양 비교

```{r, echo = FALSE}
pander(tapply(ted0405$n_chars, ted0405$bird, summary))
```

### Box Plot

```{r, echo = FALSE}
par(family = "HCR Dotum LVT")
plot(n_chars ~ bird, data = ted0405, 
     main = "마감일 이후 제출한 사람과 마감일 전에 낸 사람", 
     xlab = "제출 시점", ylab = "글자 수")
```

### t-test

```{r, echo = FALSE}
pander(t.test(n_chars ~ bird, data = ted0405))
```

## 댓글의 양이 다소 부족한 사례

### 400자 미만

```{r, echo = FALSE}
# na.omit(ted0405)$name[na.omit(ted0405)$n_chars < 400]
na.omit(ted0405)$n_chars[na.omit(ted0405)$n_chars < 400]
ted0405 %>% 
  na.omit %$%
  table(.$group, .$n_chars < 400) %>%
  `colnames<-`(c(">= 400", "< 400")) %>%
  pander
```  

## 댓글의 양이 부족한 사례

### 300자 미만

```{r, echo = FALSE, eval = TRUE}
# na.omit(ted0405)$name[na.omit(ted0405)$n_chars < 300]
na.omit(ted0405)$n_chars[na.omit(ted0405)$n_chars < 300]
ted0405 %>% 
  na.omit %$%
  table(.$group, .$n_chars < 300) %>%
  `colnames<-`(c(">= 300", "< 300")) %>%
  pander
```

## 댓글의 양이 많이 부족한 사례

### 200자 미만

```{r, echo = FALSE}
# na.omit(ted0405)$name[na.omit(ted0405)$n_chars < 200]
na.omit(ted0405)$n_chars[na.omit(ted0405)$n_chars < 200]
```

## Save

```{r, echo = FALSE}
saveRDS(ted0405, file = "TED200405.RDS")
```