---
title: "Women and Children First!"
author: "coop711"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

타이타닉호의 침몰 과정에서 **여성과 어린이를 먼저 구한다**는 원칙은 지켜졌는가?

## Data


```{r}
library(magrittr)
library(knitr)
library(pander)
library(ggplot2)
library(grid)
library(gridExtra)
load("Titanic_1801.RData")
ls()
```

## Source User Defined Functions

```{r}
source("barplot_gg.R")
source("mosaic_gg.R")
```

## Data Manipulation

```{r}
Surv_Class %>% 
  str
Surv_Class %>% 
  as.table %>% 
  str
Surv_Sex %>% 
  str
Surv_Sex %>% 
  as.table %>% 
  str
Surv_Age %>% 
  str
Surv_Age %>% 
  as.table %>% 
  str
Female_Class %>% 
  str
Child_Class %>% 
  str
```

## Plots 

### By Class

#### Barplots

```{r, fig.width = 12, fig.height = 6, warning = FALSE, message = FALSE}
b1_stack <- barplot_gg_stack(as.data.frame(as.table(Surv_Class)[2:1, ]), 
#                              ggtitle = "객실 등급별 생존/사망",
                             xlab = "객실 등급") +  
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
b1_fill <- barplot_gg_fill(as.data.frame(as.table(Surv_Class)[2:1, ]), 
#                            ggtitle = "객실 등급별 생존/사망",
                           xlab = "객실 등급") + 
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
top1 <- textGrob("객실 등급별 생존/사망", 
                 gp = gpar(cex = 1.2, fontfamily = "KoPubWorldDotum Bold"))
grid.arrange(b1_stack, b1_fill, ncol = 2, top = top1)
```

#### Mosaic Plots

```{r, fig.width = 7.2, fig.height = 6, warning = FALSE, message = FALSE}
mosaic_gg(as.table(Surv_Class)[2:1, ], 
          ggtitle = "객실 등급별 생존/사망",
          xlab = "객실 등급") +  
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
ggsave("../pics/Titanic_mosaic_ggplot01.png", width = 8, height = 6, dpi = 72)
```

### By Sex

#### Barplots

```{r, fig.width = 12, fig.height = 6, warning = FALSE, message = FALSE}
b2_stack <- barplot_gg_stack(as.data.frame(as.table(Surv_Sex)[2:1, ]), 
#                              ggtitle = "객실 등급별 생존/사망",
                             xlab = "남녀") + 
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
b2_fill <- barplot_gg_fill(as.data.frame(as.table(Surv_Sex)[2:1, ]), 
#                            ggtitle = "객실 등급별 생존/사망",
                           xlab = "남녀") + 
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
top2 <- textGrob("남녀별 생존/사망", 
                 gp = gpar(cex = 1.2, fontfamily = "KoPubWorldDotum Bold"))
grid.arrange(b2_stack, b2_fill, ncol = 2, top = top2)
```

#### Mosaic Plots

```{r, fig.width = 7.2, fig.height = 6, warning = FALSE, message = FALSE}
mosaic_gg(as.table(Surv_Sex)[2:1, ], 
          ggtitle = "남녀별 생존/사망", 
          xlab = "객실 등급") +  
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
ggsave("../pics/Titanic_mosaic_ggplot02.png", width = 8, height = 6, dpi = 72)
```

### By Age

#### Barplots

```{r, fig.width = 12, fig.height = 6, warning = FALSE, message = FALSE}
b3_stack <- barplot_gg_stack(as.data.frame(as.table(Surv_Age)[2:1, ]), 
#                              ggtitle = "객실 등급별 생존/사망",
                             xlab = "어린이와 어른") + 
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
b3_fill <- barplot_gg_fill(as.data.frame(as.table(Surv_Age)[2:1, ]), 
#                            ggtitle = "객실 등급별 생존/사망",
                           xlab = "어린이와 어른") +  
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
top3 <- textGrob("어린이와 어른의 생존/사망", 
                 gp = gpar(cex = 1.2, fontfamily = "KoPubWorldDotum Bold"))
grid.arrange(b3_stack, b3_fill, ncol = 2, top = top3)
```

#### Mosaic Plots

```{r, fig.width = 7.2, fig.height = 6, warning = FALSE, message = FALSE}
mosaic_gg(as.table(Surv_Age)[2:1, ], 
          ggtitle = "어린이/어른 생존/사망", 
          xlab = "객실 등급") + 
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
ggsave("../pics/Titanic_mosaic_ggplot03.png", width = 8, height = 6, dpi = 72)
```

### Female by Class

#### Barplots

```{r, fig.width = 12, fig.height = 6, warning = FALSE, message = FALSE}
b4_stack <- barplot_gg_stack(as.data.frame(as.table(Female_Class)[2:1, ]), 
#                              ggtitle = "객실 등급별 생존/사망",
                             xlab = "객실 등급") + 
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
b4_fill <- barplot_gg_fill(as.data.frame(as.table(Female_Class)[2:1, ]), 
#                            ggtitle = "객실 등급별 생존/사망",
                           xlab = "객실 등급") + 
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
top4 <- textGrob("객실 등급별 여성 생존/사망", 
                 gp = gpar(cex = 1.2, fontfamily = "KoPubWorldDotum Bold"))
grid.arrange(b4_stack, b4_fill, ncol = 2, top = top4)
```

#### Mosaic Plots

```{r, fig.width = 7.2, fig.height = 6, warning = FALSE, message = FALSE}
mosaic_gg(as.table(Female_Class)[2:1, ], 
          ggtitle = "객실 등급별 여성 생존/사망", 
          xlab = "객실 등급") +  
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
ggsave("../pics/Titanic_mosaic_ggplot04.png", width = 8, height = 6, dpi = 72)
```

### Children by Class

#### Barplots

```{r, fig.width = 12, fig.height = 6}
b5_stack <- barplot_gg_stack(as.data.frame(as.table(Child_Class)[2:1, ]), 
#                              ggtitle = "객실 등급별 생존/사망",
                             xlab = "객실 등급") + 
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
b5_fill <- barplot_gg_fill(as.data.frame(as.table(Child_Class)[2:1, ]), 
#                            ggtitle = "객실 등급별 생존/사망",
                           xlab = "객실 등급") +  
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
  theme(plot.title = element_text(hjust = 0.5))
top5 <- textGrob("객실 등급별 어린이 생존/사망", 
                 gp = gpar(cex = 1.2, fontfamily = "KoPubWorldDotum Bold"))
grid.arrange(b5_stack, b5_fill, ncol = 2, top = top4)
```

#### Mosaic Plots

```{r, fig.width = 7.2, fig.height = 6}
mosaic_gg(as.table(Child_Class)[2:1, -4], 
          ggtitle = "객실 등급별 어린이 생존/사망", 
          xlab = "객실 등급") +  
  scale_fill_manual(name = "", labels = c("생존", "사망"), values = rainbow(2)[2:1]) +
#  ggtitle("객실 등급별 어린이 생존/사망") + 
  theme(plot.title = element_text(hjust = 0.5)) 
ggsave("../pics/Titanic_mosaic_ggplot05.png", width = 8, height = 6, dpi = 72)
```


