---
title: "US Top Income Share vs Tax Rates (1913 ~ 2017)"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

## Data Preparation

준비한 자료는  [E. Saez 교수의 홈페이지](http://elsa.berkeley.edu/~saez/)에 있는 `TabFig2017prel.xls` 와 [Tax Foundation](http://taxfoundation.org/)에서 제공하는 자료를 손봐서 불러들인 것이다. 

```{r, data preparation, message = FALSE, echo = FALSE, results = 'hide'}
options(digits = 2)
library(knitr)
load("US_top_income_shares_vs_tax_rates_2017.RData")
```

이 중에서 소득 상위 1%(`P99_100`)몫과 최고세율(Marginal Tax Rates) 간의 관계를 살펴보자

```{r, top 1 percent shares vs MTR, echo = TRUE, fig.width = 12, fig.height = 6.75}
# png(file = "../pics/US_Top_Income_Share_vs_MTR_72dpi_en.png", width = 864, height = 486)
# png(file = "../pics/US_Top_Income_Share_vs_MTR_300dpi_en.png", width = 1280, height = 720)
par(mar = c(5, 6, 4, 6) + 0.1)
plot(P99_100 ~ Year, 
     data = top_income_tax, 
     type = "b", 
     pch = 17, 
     axes = FALSE, 
     ann = FALSE, 
     xlim = c(1910, 2020), ylim = c(5, 25))
box()
axis(side = 1, 
     at = seq(1910, 2020, by = 10), 
     labels = seq(1910, 2020, by = 10))
axis(side = 2, 
     at = seq(5, 25, by = 5), 
     labels = seq(5, 25, by = 5), 
     las = 1, 
     ylab = "Top Income Share")
mtext("Top Income Share(%)", 
      side = 2, 
      line = 3)
par(new = TRUE)
plot(Marginal ~ Year, 
     data = top_income_tax, type ="l", 
     lty = 2, 
     lwd = 2, 
     col = "red", 
     axes = FALSE, 
     ann = FALSE, 
     xlim = c(1910, 2020), 
     ylim = c(0, 100))
axis(side = 4, 
     at = seq(0, 100, by = 20), 
     labels = seq(0, 100, by = 20), 
     las = 1)
mtext("Marginal Tax Rates(%)", 
      side = 4, 
      line = 3)
title(main = "Top 1% Income Share and Top Marginal Tax Rate", 
      xlab = "Year")
text(x = 1980, y = 75, 
     labels = "Top Marginal Tax Rates", 
     cex = 1.2)
text(x = 1960, y = 17, 
     labels = "Top 1% Income Shares", 
     cex = 1.2)
# dev.copy(png, file ="../pics/US_Top_Income_Share_vs_MTR_en.png", width = 960, height = 540)
# dev.off()
``` 

<!--## 뒷 정리

```{r, save.image}
save.image(file = "US_top_income_shares_vs_tax_rates_2017_v2.RData")
```
-->
