---
title: "US Top Income Share vs Tax Rates (1913 ~ 2017) - Data"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

## Data Preparation

준비한 자료는  [E. Saez 교수의 홈페이지](http://elsa.berkeley.edu/~saez/)에 있는 `TabFig2017prel.xls` 와 [Tax Foundation](http://taxfoundation.org/)에서 제공하는 자료를 손봐서 불러들인 것이다. 

```{r, data preparation, message = FALSE, echo = FALSE, results = 'markup'}
options(digits = 2)
library(xlsx)
library(knitr)
library(reshape2)
library(tidyverse)
library(magrittr)
load("US_top_income_shares_2017.RData")
tax_rates <- read.table("../data/federal_income_tax_rates.txt", 
                        skip = 1, header = FALSE)
names(tax_rates) <- c("Year", "Lowest", "Marginal")
top_income_tax <- cbind(US_top_income_shares_17[c("Year", "P99_100")], tax_rates[2:3])
```

선형변환에 사용할 함수 작성  `q = x`로 하면 변수의 관찰값 전체를 변환. `q`는 그 중 일부의 변환된 값을 보고자 할 때 입력

```{r}
z <- function(x, q, a = min(x), b = max(x)) {
  (q - a) / (b - a)
}
#> 0애서 1사이의 범위로 변환
top_income_tax$P99_100_z <- top_income_tax$P99_100 %>%
  z(., .)
top_income_tax$Marginal_z <- top_income_tax$Marginal %>%
  z(., .)
kable(top_income_tax)
M_tbl <- top_income_tax %>%
  select(c("Year", "P99_100_z", "Marginal_z")) %>%
  as_tibble %>%
  gather(key = "Variables", value = "Values", -Year) %>%
  mutate(Variables = factor(Variables, levels = c("P99_100_z", "Marginal_z")))
str(M_tbl)
M_melt <- melt(data.frame(top_income_tax[c("Year", "P99_100_z", "Marginal_z")]),
       id.vars = "Year", 
       measure.vars = c("P99_100_z", "Marginal_z"),
       variable.name = c("Variables"),
       value.name = "Values")
str(M_melt)
```

## Save

```{r, save.image}
save.image(file = "US_top_income_shares_vs_tax_rates_2017.RData")
```

