---
title: "Weighted Dice Simulation"
author: "데이터과학융합스쿨 이기원"
date: "`r Sys.Date()`"
output: html_document
---

## Simulation
  
```{r}
source("./roll.R")
ls()
replicate(20, roll())
N <- 10000
rolls <- replicate(N, roll())
table(rolls)
options("digits")
options(digits = 2)
table(rolls)/N
table(rolls)/N * 36
options(digits = 1)
table(rolls)/N * 36
options(digits = 7)
```

## histogram

```{r}
library(ggplot2)
qplot(c(1, 2, 2, 2, 3, 3), binwidth = 1)
qplot(c(1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 4), binwidth = 1)
qplot(rolls, binwidth = 1)
```

## Weighted Dice

```{r}
# roll_w <- roll
# fix(roll_w)
roll_w <-
  function() {
    die <- 1:6
    dice <- sample(die, 
                   size = 2, 
                   replace = TRUE, 
                   prob = c(rep(1/8, 5), 3/8))
    sum(dice)
    }
roll_w
replicate(20, roll_w())
N <- 10000
rolls_w <- replicate(N, roll_w())
table(rolls_w)
options("digits")
options(digits = 2)
table(rolls_w)/N
table(rolls_w)/N * 64
options(digits = 1)
table(rolls_w)/N * 64
```

## histogram

```{r}
qplot(rolls_w, binwidth = 1)
```

## dump

```{r}
dump(list = "roll_w", file = "./roll_w.R")
```

## Comments

Tell me what you have learned.